name: duck_router
description: "Intent-based router for Flutter mobile app, supporting deep linking, nesting and more."
version: 5.1.3
repository: https://github.com/JaspervanRiet/duck_router
issue_tracker: https://github.com/JaspervanRiet/duck_router/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

topics:
  - navigation
  - intents
  - bottom-bar
  - deep-linking
