name: duck_router

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "flutter/packages/duck_router/**"
      - ".github/workflows/duck_router.yaml"

jobs:
  build:
    runs-on: [mobile, self-hosted]
    defaults:
      run:
        working-directory: flutter/packages/duck_router

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good

      - uses: bluefireteam/melos-action@v3
        with:
          melos-version: ${{ vars.MELOS_VERSION }}

      - name: âœ¨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: ğŸ•µï¸ Analyze
        run: flutter analyze lib test

      - name: ğŸ§ª Run Tests
        run: very_good test -j 4 --optimization --coverage --test-randomize-ordering-seed random

      - name: ğŸ“Š Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          path: packages/duck_router/coverage/lcov.info
          exclude: "**/*.g.dart **/*.freezed.dart **/*.mapper.dart"
          min_coverage: 90
